### ISSUE TITLE
preDispatch error

### ISSUE THREAD

**Issue by choppe3766** [dachcom-digital/pimcore-formbuilder#1]
After install the plugin, i get on every document these error:

Declaration of Formbuilder\Controller\Plugin\Frontend::preDispatch() should be compatible with Zend_Controller_Plugin_Abstract::preDispatch(Zend_Controller_Request_Abstract $request)

from this file: 
/plugins/Formbuilder/lib/Formbuilder/Controller/Plugin/Frontend.php

Arguments
"Declaration of Formbuilder\Controller\Plugin\Frontend::preDispatch() should be compatible with Zend_Controller_Plugin_Abstract::preDispatch(Zend_Controller_Request_Abstract $request)"

I have installed pimcore 4.1.1.

**Comment by solverat** [comment]
Thanks! Fixed with 11a463f.

**Comment by choppe3766** [comment]
Hi Stefan,

is there a short manual which describes an how-to for use the form builder?
I have some experience with the Zend-Formbuilder, but it seems your forbidder work „a little bit“ different.

Thans for your help and regards
Chris


Mit freundlichen Grüßen

Chris Hoppe
Fa. Business Lösungen

Fraunhoferstr. 1
83626 Valley

Tel.: +49 (0)8024 6467412
Fax: +49 (0)8024 6467413
Mobil: +49 (0)173 8086199 
Email: chris.hoppe@bl-internet.de
Web: http://www.bl-internet.de
