### ISSUE TITLE
Output Workflows (Email Channel, Object Generator Channel)

### ISSUE THREAD

**Issue by solverat** [dachcom-digital/pimcore-formbuilder#114]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | currently possible

## Idea
Allow to define a pimcore class in each form which should get mapped with.

## Implementation
- Create a pimcore class
- Choose class in form base tab from a dropdown
- Every form field should show a dropdown with all class properties (also check possibility, e.g. do not allow relation fields for example)
- If a form is valid, all mapped fields should get applied to the available object properties
- Store new object

## Additions
- Add Events in different creation states
- Allow to define key and uniqueness

**Comment by scrummer** [comment]
We should also provide a way to set an object before the form is rendered to pre-fill the mapped fields with the values from the object fields and then on form submit, update the existing object.

**Comment by solverat** [comment]
## Roadmap
- In summary, we want to allow you to define several output workflows per form
- We also want to simplify the configuration layer: All of it should happen at form configuration
- We also want to keep BC, so we'll introduce a `fallbackOutputWorkflow` which handles the current "mail" + "copy mail" behavior, which currently needs to be defined in area configuration

## Output Workflows
Create Output Workflows at every Form in its configuration panel

- Output Workflows (`1:N`)
  - Success Handler (`1:1`)
     - Message: Snippet/Document (same as `mail_successfully_sent`)
     - Redirect (Document, same as `mail_successfully_sent`)
       - Flash Message (same as `mail_successfully_sent_flash_message`)
  - Channels (`1:N`)
     - Email Channel
     - Object Channel
     - Custom Channel

### Output Workflow  Channel
- Registered via Symfony Tag
- Each Channel comes with a dedicated ExtJs class

### Output Workflow: Email Channel
- Field: Add Mail Editor Configuration Panel
- Field: Drop Mail Template
- Field: `mail_force_plain_text` Configuration
- Field: `mail_disable_default_mail_body` Configuration

### Output Workflow: Object Channel
- Field: Define storage folder
- Choose between `create new object` and `append data to existing object`
   - If existing object: choose field collection of selected object class and start field collection mapping
   - If new object: initial object mapping
- Mapping: object class selection:
   - Default field: drag form field to object field, if possible, allow mapping (similar to CSV import mapping)
   - Repeater Field: Choose between:
     - Store as child objects
       - Mapping: Object class selection → map fields (Back to "Default field")
     - Store in field collection
       - Mapping: Field collection selection → map fields (Back to "Default field")

### Mail Editor
- Deprecate global mail editor

### Conditional Logic
- Deprecate Email Behavior
- Introduce new Action "Change Output Channel"

## Area Element
- If workflows have been defined, do not allow defining emails / copy emails, otherwise keep config at it is
- If workflows have been defined and `output workflows` === `1`: Only show workflow
- If workflows have been defined and  `output workflows` > `1`: Show dropdown with workflows

## Form
- Allow validation before storing (Example: Repeater element is a user for a registration → allow checking duplicates)
- Allow to do some process before final storing (Example: Make payment or similar)

**Comment by solverat** [comment]
WIP: https://recordit.co/YaBAlRDP78

**Comment by solverat** [comment]
DONE!
