### ISSUE TITLE
PHP demo compatibility

### ISSUE THREAD

**Issue by julmot** [dachcom-digital/pimcore-formbuilder#119]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Thanks for building this plugin. It seems to fill the missing form functionalities that users expect to exist by default. 

I've installed pimcore-formbuilder successfully based on [the Pimcore Twig demo](https://github.com/pimcore/demo-basic-twig). However, it didn't work based on the [eCommerce demo](https://github.com/pimcore/demo-ecommerce) which doesn't make use of Twig.

Therefore I'm asking myself whether this is expected or not? If it is expected, it would be great to have this documented in the README.

**Comment by solverat** [comment]
Hey @julmot, yes that's true. FormBuilder (and all other dachcom-bundles) does not support php templates. I'll add a doc-hint for that.

**Comment by julmot** [comment]
@solverat Thanks for the response. In this regard, maybe you could also add how to create a form that is required in the form field?

![topic](https://user-images.githubusercontent.com/8310677/44412522-6fc30100-a569-11e8-958a-8d7c1696cab7.png)

Maybe it's just me, but since there doesn't seem to be a new document type or class to create a "form" object, I don't know how to create it.

**Comment by solverat** [comment]
it's right there: 💪 
![bildschirmfoto 2018-08-21 um 17 43 09](https://user-images.githubusercontent.com/700119/44412630-adc02500-a569-11e8-8f54-6a620cb7b911.png)
