### ISSUE TITLE
Fileupload failed with bigger files up to 2.5 MB

### ISSUE THREAD

**Issue by plexmaniax** [dachcom-digital/pimcore-formbuilder#120]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Fileupload in formbuilder failed if files are bigger than 2.5 MB.
The file will be accepted, but the zip on the server cointains 0 KB Files. 

Tested with 2.5 MB and 5 MB CSV Files

**Comment by solverat** [comment]
fixed with #121
