### ISSUE TITLE
This could really use some better documentation.

### ISSUE THREAD

**Issue by justbane** [dachcom-digital/pimcore-formbuilder#124]
I have been struggling for a day trying to get the forms I create to work. I specify actions select ajax and it only ever goes to /en/form-control/parse... that lives nowhere on my install.

Could you provide some documentation with some step by step?

**Comment by solverat** [comment]
@justbane the route you mentioned is defined in the bundle route configuration, it's just simple symfony standard. You'll find some further infos about ajax submission [here](https://github.com/dachcom-digital/pimcore-formbuilder/blob/master/docs/20_AjaxForms.md#ajax-forms).
