### ISSUE TITLE
Folders in form tree

### ISSUE THREAD

**Issue by RuudvdvNB** [dachcom-digital/pimcore-formbuilder#134]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes/no

After a few months we have created more than 50 different forms and everything works great!

But we are currently creating even more forms and it's getting harder to find a form we need to change. Is it possible to group forms in directories/subdirectories in the form tree?

**Comment by solverat** [comment]
Hey @RuudvdvNB, yes that's a good hint. Maybe we should do the same as pimcore does in the class builder tree (Using a group name per form).

**Comment by RuudvdvNB** [comment]
@solverat yes that would be a very good solution! Any thoughts when you think this will be implemented? :D
