### ISSUE TITLE
Unable to add form to document

### ISSUE THREAD

**Issue by Yivan** [dachcom-digital/pimcore-formbuilder#136]
Hello,

We just install the last dev-master version on a fresh Pimcore 5 with demo-basic skeleton.

We created a minimal form:

![form1](https://user-images.githubusercontent.com/9025839/48194723-18555580-e34e-11e8-8231-66afb6e18f19.png)

And add it to a document:

![form2](https://user-images.githubusercontent.com/9025839/48194729-2014fa00-e34e-11e8-9953-a6cdd9c978a0.png)

But nothing is displayed...

Is it a bug or there is something more to configure/develop ?
In formbuilder for Pimcore 4 it was working loke this.

Thanks!

**Comment by solverat** [comment]
There should be a edit icon on the right top corner of your added form area.
Also: Please make sure you have enabled the debug mode in system settings maybe you'll notice an exception.

**Comment by solverat** [comment]
I just pushed something to improve the error output while a area gets generated. Have you "installed the formbuilder bundle in extensionmanager after upgrading? see https://github.com/dachcom-digital/pimcore-formbuilder/blob/master/UPGRADE.md#update-from-version-242-to-version-250

**Comment by solverat** [comment]
I'm not able to reproduce this. i just have a simple form on a plain pimcore installation: 

## area placed without selected form
![bildschirmfoto 2018-11-08 um 15 40 42](https://user-images.githubusercontent.com/700119/48205692-e9021100-e36c-11e8-9642-58f9ffd9e756.png)

## area placed with a selected form
![bildschirmfoto 2018-11-08 um 15 41 29](https://user-images.githubusercontent.com/700119/48205693-e99aa780-e36c-11e8-8d26-118f8f0bfe5f.png)

**Comment by Yivan** [comment]
Hum did you try on a fresh install in the same way i inserted it on the page of the Pimcore basic demo skeleton ? Should it work ?

**Comment by solverat** [comment]
yes. i tested it on fresh pimcore 5.4 and pimcore 5.5 installation.

**Comment by Yivan** [comment]
I just tried again and it seems to work ok now. I think maybe the changes you done yesterday corrected the problem.
So it works great now! Thanks a lot for having looking in it.
You can close this issue.

**Comment by solverat** [comment]
👍
