### ISSUE TITLE
Date field throw an error

### ISSUE THREAD

**Issue by Yivan** [dachcom-digital/pimcore-formbuilder#137]
Hello,

Using date fields configured like this:

![form](https://user-images.githubusercontent.com/9025839/48434489-1a6a4a80-e77a-11e8-86a3-8f7e44d1b1a2.png)

Display an error:

![error](https://user-images.githubusercontent.com/9025839/48434568-543b5100-e77a-11e8-952b-0bde1d8fad1d.png)

Have we made something wrong or is it a bug ?

Thanks.

**Comment by Kalsarix** [comment]
The exact problem comes with the customization of the Months' field.
If the Months field is left blank, evertything is OK and the dropdown menu in Front-Office lists "Jan", "Feb", "Mar", etc.
The error message appears by filling custom values in the Months' field (custom values for the two others fields "Days" and "Years" is OK).

Thank you for your help!

**Comment by solverat** [comment]
That's because you have to use integer as values:
- https://symfony.com/doc/current/reference/forms/types/date.html#days
- https://symfony.com/doc/current/reference/forms/types/date.html#months
