### ISSUE TITLE
Improve Form Validation in Backend

### ISSUE THREAD

**Issue by Yivan** [dachcom-digital/pimcore-formbuilder#138]
Hello !

As a backend user, if i create a form and the field is invalid i can no more delete it easily.
I have to close the form and reopen it.

Step to reproduce (tested on last stable Chrome on Windows):
- create an empty form
- add a text input field and fill nothing
- right click on the "Text Type" field to delete it
=> a popin "Some form elements are invalid" is displayed and the context menu to be able to delete it is not displayed
=> if i click the "OK" button, and right click on the "Text Type" field again, nothing happens.

Here is a screenshot please:

![form](https://user-images.githubusercontent.com/9025839/48476233-c6ee1000-e7fe-11e8-8581-6f54d3e3cb25.png)

Proposition:
- like other Pimcore behaviour (like the class editor for instance), don't trigger the verification on the right click, so we can delete the fields.

Thanks a lot!

**Comment by solverat** [comment]
Just enter something in "display name" and you're able again to remove the field. There is no need to close and re-open a form.

**Comment by Yivan** [comment]
Thanks for your fast answer!
Yes sure we can do this, but this is not very friendly to must fill dummy values to be able to delete it after.
And the right click doesn't work after clicking "OK" (it does nothing), it's a strange behaviour.

**Comment by Yivan** [comment]
Hello, i just checked the new way form is validated and all is great now!! Thanks again for this!
