### ISSUE TITLE
Isn't it possible to group fields by Bootstrap .form-row

### ISSUE THREAD

**Issue by mittererr** [dachcom-digital/pimcore-formbuilder#139]
Isn't it possible to combine two or more fields by Bootstrap .form-row?

**Comment by solverat** [comment]
@mittererr: Nope, currently the only way is to choose templates on field-level. **BUT!** There will be a new Field-Type (Working-Title: `Stack`,  Symfony CollectionType basically) which allows you to add different types of container:
- `FieldSet`: Group Fields within a Wrapper-Element and custom attributes (like "class" for example)
- `Repeater`: Group Fields and allow them to repeat in front-end (With some settings like "min", "max", "add more label" etc.)

**Comment by solverat** [comment]
Closing in favor of #68.
