### ISSUE TITLE
File submited by the form can be overwrite if same name.

### ISSUE THREAD

**Issue by Yivan** [dachcom-digital/pimcore-formbuilder#14]
It seems that the file uploaded in the form is saved "as it" on the destination folder.
No check seems to be done if the file exist. So somes users could delete other user files.

For instance, a form to upload a CV (curriculum vitae) for user applying for a job, many of them will have cv.pdf as name, so many could be overwrited.
As a basis, maybe filename could be postfixed with timestamp if the file already exist. It will prevent loosing information submited by users of the form.

All following are more improvements:

---
**1- Dynamic name**
A great addition to this would be the possibility to define dynamic name "%fistname %lastname" (and keeping the same extention, wich will do for John Doe user sending his cv: "John Doe.pdf". More easy to find back files depending of the form.
**Maybe i am all wrong and all of this can be done by make custom code and use "Hoock class" or "Static class action" ? Those are not explained on the documentation, maybe it could be added to documentation (with the paramters received/sended and when the hook happen).**

**2- Attached to the email**
Here is an other imprvement wich could be done, to help people receiving the email:
Actually, all the plugin is user-friendly, meaning without any coding an end user can create form, email, associate them. It seems mail will be send only in ajax mode (using normal mode need custom code if i am right ?). Concerning the file, is there a way the user can attache it to the mail ? (actually i think he can create a placeholder with the file name and after download it by FTP... not very user firendly).

**3- Security**
Is there any security prevention on file upload ? I didn't check the code, but could a user send a php file ? (and after he could execute it...). The user creating the form could forgot to limit the extension type... and leave a dangerous breach in the system.

---

All other form element types are just right and make a really good job. File upload was the only one wich i fill can be problematic on classic use case for end user creating form, so the purpose of this issue.
Thanks a lot!

**Comment by solverat** [comment]
Hey Yivan, at first, thanks for your detailed investigation!
The default file field didn't get much of attention from our side, you're right. :) Currently we're working on Version 1.3.0 which comes with an multi-upload field (with drag & drop, see #5). After you checked the "*multifile*" option, the new field (ajax-driven) will be active. With that, your concerns "*2- Attached to the email*" and "*3- Security*" has been worked out.

But after all, you're right: We should get rid of this nasty single file field.

**Comment by solverat** [comment]
hey @Yivan. Since fb2 is now the current feature branch, we decided to close this issue without any further changes. If you're still using fb1 you should just use the _multi file_ element.
