### ISSUE TITLE
.form-control class on file-upload field

### ISSUE THREAD

**Issue by scrummer** [dachcom-digital/pimcore-formbuilder#142]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes

### Description
In commit https://github.com/dachcom-digital/pimcore-formbuilder/commit/9b6d994e633517328461b340b8e120ad746411c3#diff-eb8690b256e0271995136d2761945b59R8 the `.form-control` class has been added to the `.dynamic-multi-file` wrapper of the file-uploader field.
When using Bootstrap together with the fine-uploader (as suggested in the docs) this results (in my case) in the following behaviour:
![image](https://user-images.githubusercontent.com/15173170/50276731-f36efa80-0442-11e9-9ac1-67678f698147.png)

In the bootstrap v4 docs it says, that the `.form-control` should be used for `<input>`, `<select>` and `<textarea>` fields (http://getbootstrap.com/docs/4.1/components/forms/#form-controls).

### So now the question:
Is the class really wanted here?

**Comment by solverat** [comment]
The form-control is required for validation. Since we never experienced your behavior in our projects, i‘m going to close this ticket for now. If you have a better idea how to deal with this in combination with validation feel free to reopen it or even better: send us a PR! 😊
