### ISSUE TITLE
Add attributes to Fieldsets

### ISSUE THREAD

**Issue by dpfaffenbauer** [dachcom-digital/pimcore-formbuilder#146]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

Add Attributes section from here:

<img width="1643" alt="bildschirmfoto 2019-02-22 um 09 06 28" src="https://user-images.githubusercontent.com/5981845/53228332-2cb12a00-3681-11e9-8521-2224b203b5ce.png">

to here:

<img width="929" alt="bildschirmfoto 2019-02-22 um 09 06 09" src="https://user-images.githubusercontent.com/5981845/53228317-1efba480-3681-11e9-93b2-f11e8c91cc3e.png">

**Comment by solverat** [comment]
done with #151.
