### ISSUE TITLE
HTML Tag Type: allow adding html content

### ISSUE THREAD

**Issue by dpfaffenbauer** [dachcom-digital/pimcore-formbuilder#147]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

Allow Adding Content to the HTML Tag Type. Maybe also allow to choose a pimcore snippet? (somehow related to https://github.com/dachcom-digital/pimcore-formbuilder/issues/111)

**Comment by solverat** [comment]
There is already a snippet type - not good enough?

**Comment by dpfaffenbauer** [comment]
that is exactly what I need. 

Cheers bro
