### ISSUE TITLE
Changing email recipient and subject

### ISSUE THREAD

**Issue by thgross** [dachcom-digital/pimcore-formbuilder#161]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes

Is it possible to dynamically change the email recipient and email subject?

In our application we render a form in dynamically created product pages, and we want to set the email recipient and email subject from the product database.

We render the form in the controller, but we don't know how to access the email settings.

The FORM_MAIL_PRE_SUBMIT event might be a way to do this, but there seems to be no way to send custom data to the event.

**Comment by solverat** [comment]
Hey @thgross,

as you mentioned, `FORM_MAIL_PRE_SUBMIT` is the perfect place:

```php
<?php 

protected function parse(MailEvent $event)
{
   $form = $event->getForm();
   $mail = $event->getEmail();

   // do your work [...]

   $event->setEmail($mail);
}
```

should do the trick.

**Comment by thgross** [comment]
> 
> 
> Hey @thgross,
> 
> as you mentioned, `FORM_MAIL_PRE_SUBMIT` is the perfect place:

Thank you for your reply.

I know that's the place to change the email settings. However, how am I able to add my custom target email / subject to either `$form` or `$mail` when using the controller to render the form:
https://github.com/dachcom-digital/pimcore-formbuilder/blob/master/docs/0_Usage.md#iii-controller

Where do I put custom data to access it in the `FORM_MAIL_PRE_SUBMIT` event?

**Comment by solverat** [comment]
Regardless of the rendering type, you always need to add your custom event class to modify form data or the mail template. 

Form Events: https://github.com/dachcom-digital/pimcore-formbuilder/blob/master/docs/70_Events.md

Mail Events: https://github.com/dachcom-digital/pimcore-formbuilder/blob/master/docs/70_Events.md#mail-pre-submit
