### ISSUE TITLE
Make honeypot field optional

### ISSUE THREAD

**Issue by ihmels** [dachcom-digital/pimcore-formbuilder#167]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

In Google Chrome there is a problem with the honeypot field. If you let Chrome fill in the fields, the honeypot field will also be filled in (in my case with a zip code).

In my opinion it would be better if it could be configured whether the honeypot field should be used (analogous to CSRF or per form).

**Comment by solverat** [comment]
We‘re aware of that, please check the docs regarding your issue: 

https://github.com/dachcom-digital/pimcore-formbuilder/blob/master/docs/90_FrontendTips.md#hide-the-honeypot-for-real

**Comment by solverat** [comment]
There is currently not plan to add this but i don't think this would be a tricky thing (Maybe adding a new configuration flag? `formbuilder.use_honeypot_field = true` for example)

PRs are always welcome!
