### ISSUE TITLE
on validation, must-field-message changes checkbox-field

### ISSUE THREAD

**Issue by pixel81k** [dachcom-digital/pimcore-formbuilder#177]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

On validation, the labels of required checkboxes are moved below the checkbox to give place for the validation-message ("Must not be empty...") - the html-code structure is changed.
For all other fields, the message appears below the form-element, for checkboxes, the label is moved below and the message appears at the place of it. Also quite interesting, i still have to click the (moved) label to check the checkbox

![before](https://user-images.githubusercontent.com/6976087/60414127-91543680-9bd7-11e9-803c-d10e8e64cd5e.png)
![after](https://user-images.githubusercontent.com/6976087/60414129-91543680-9bd7-11e9-881f-39af844e3338.png)

![code before](https://user-images.githubusercontent.com/6976087/60414248-e132fd80-9bd7-11e9-9373-c9283e6bd98d.png)
![code after](https://user-images.githubusercontent.com/6976087/60414247-e132fd80-9bd7-11e9-8595-a322ec0ab36e.png)

**Comment by Homer0815** [comment]
I have a weird behaviour on the checkbox-field too. When using the the form **without** Ajax, two validation messages will be shown: 

![image](https://user-images.githubusercontent.com/10532676/87661008-38166100-c760-11ea-8f00-774d4410d45e.png)

**Comment by Homer0815** [comment]
Bump 👍
