### ISSUE TITLE
Formbuilder

### ISSUE THREAD

**Issue by rushit-credencys** [dachcom-digital/pimcore-formbuilder#178]
how to **get data in formbuilder inputs** bcz i want to edit/update data using formbuilder fields.
I have use this code but it's create new form and i wand to all fields data in existing form.

          $task = new example();
                $task->setDidWell('DidWell');
                $task->setDidNotWell('DidNotWell');
                $task->setDidDifferently('DidDifferently');
                

                $form = $this->createFormBuilder($task)
                    ->add('didWell', TextType::class)
                    ->add('didNotWell', TextType::class)
                    ->add('didDifferently', TextType::class)
                    ->add('save', SubmitType::class, ['label' => 'Create Task'])
                    ->getForm();

                return $this->render('Form/Theme/Bootstrap/form_row.html.php', [
                    'form' => $form->createView(),
                ]);

**Comment by solverat** [comment]
I have no idea what you're trying to achieve but it looks like you don't even use the pimcore formbuilder itself. Please be sure that you're familiar with the symfony form component. Then you should take a look at the [event documentation here](https://github.com/dachcom-digital/pimcore-formbuilder/blob/master/docs/70_Events.md).

Feel free to reopen this issue again.
