### ISSUE TITLE
Formbuilder.comp.form.getFields add a deep / recursive parameter

### ISSUE THREAD

**Issue by msphn** [dachcom-digital/pimcore-formbuilder#188]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no?

At the moment, this function is unable to deliver all fields of a form. To improve this, I'd suggest a recursive parameter, so the previous use of this method doesn't break. getFields is often used to find root form elements.

In addition to this, I'd like to make use of those fields in the condition builder. 

I maybe find time to look into that myself, but I'd like to hear your feedback first before investing time.

**Comment by msphn** [comment]
@solverat could you give some feedback?

**Comment by solverat** [comment]
Well, that's a big deal. Currently, no container (sub) fields are allowed on purpose. A collection sub item for example is hard to handle in conditional logic and also in mail renderings. 

So, we need to dive deep with this. Allowing sub-fields in extjs is just the tip of the iceberg and also the easiest step. But how exactly should we handle sub-fields later on?

**Comment by msphn** [comment]
I had in mind flattening the fields for the conditional logic, but I didn't dive into the further logic yet.

**Comment by solverat** [comment]
This has been fixed with https://github.com/dachcom-digital/pimcore-formbuilder/issues/232. Conditional Logic supports:
- Container types (Repeater, Fieldset)
- Nested fields in fieldset fields

Nested repeater fields are still unsupported (and stays unsupported forever I guess).
