### ISSUE TITLE
checkbox for symfony-html5 in date-typefield

### ISSUE THREAD

**Issue by pixel81k** [dachcom-digital/pimcore-formbuilder#190]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

in symfony there is support to allow/disallow use of html5 type="date" in date-fieldtype. 
Enhance formbuilder config to allow set/unset this field and transport it to symfony

**Comment by solverat** [comment]
fixed with #191

**Comment by solverat** [comment]
@pixel81k there is an error if you open an existing form with checkboxes:

![image](https://user-images.githubusercontent.com/700119/64233271-04d63500-cef4-11e9-9d0a-c6e6d0da897f.png)
