### ISSUE TITLE
How to set the type (text, email etc) for input fields?

### ISSUE THREAD

**Issue by thgross** [dachcom-digital/pimcore-formbuilder#192]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes

Formbuilder 3.0.2: I can't find a way to change the input type. Is it even possible?

**Comment by solverat** [comment]
Hey @thgross. You cannot change the type itself. Input field is using text, Email type is using "email".  If you need more of them, you can easily [add them by yourself](https://github.com/dachcom-digital/pimcore-formbuilder/blob/master/docs/40_CustomFormType.md).
