### ISSUE TITLE
Fieldsets with a class attribute throw exception

### ISSUE THREAD

**Issue by justbane** [dachcom-digital/pimcore-formbuilder#197]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

When you add a fieldset to a form and then add an attribute of class (have not checked with other attributes) you will get a twig exception:
```An exception has been thrown during the rendering of a template ("Warning: trim() expects parameter 1 to be string, array given").```

**Comment by solverat** [comment]
@justbane thanks for reporting. I'll have a look at it!

**Comment by solverat** [comment]
@justbane mhm.. just tried it on my test environment and everything works well. 

My form setup:
![image](https://user-images.githubusercontent.com/700119/73671163-ba2b3580-46aa-11ea-87f6-e56a27da84ac.png)

Frontend:
![image](https://user-images.githubusercontent.com/700119/73671223-d333e680-46aa-11ea-9172-eb133252fea2.png)

Maybe you can post some screenshots eg. exception stack trace?

**Comment by solverat** [comment]
Closed due to inactivity. Feel free to reopen it!
