### ISSUE TITLE
Attempted to load class "FormBuilderEvents" from namespace "FormBuilderBundle". Did you forget a "use" statement for another namespace?

### ISSUE THREAD

**Issue by tymon82** [dachcom-digital/pimcore-formbuilder#198]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

After `composer require dachcom-digital/formbuilder:^3.0.0`
Bundle didn't apper in pimcore extension installer
executing `bin/console pimcore:bundle:enable FormBuilderBundle` gives: `[ERROR] Bundle "FormBuilderBundle" is no valid bundle identifier`
executing `bin/console pimcore:bundle:install FormBuilderBundle` gives `  Bundle "FormBuilderBundle" does not exist or it is not enabled. Maybe you forgot to add it in the registerBundles() method of your AppKernel.php file?`

Adding bundle in AppKernel `$collection->addBundle(new \FormBuilderBundle\FormBuilderEvents);` gives `Attempted to load class "FormBuilderEvents" from namespace "FormBuilderBundle". Did you forget a "use" statement for another namespace?`

In autoload_psr4: `'FormBuilderBundle\\' => array($vendorDir . '/dachcom-digital/formbuilder/src/FormBuilderBundle'),`

Using Pimcore 6.2, Symfony 4.2

**Comment by solverat** [comment]
You don't have to register FormBuilder by adding it to the AppKernel.
I think there is something wrong within your composer setup. As long the bundle is not visible in the pimcore extension manager, it's simple not available.

**Comment by fritzbrandbiz** [comment]
Hi What is the solution to this problem? I have tried to recreate 3 bitnami instances and all have the same problem.

**Comment by fritzds** [comment]
hi which part fo the kernell should i add it/ thanks. sorry im new to pimcore. 


<?php
/**
 * Pimcore
 *
 * This source file is available under two different licenses:
 * - GNU General Public License version 3 (GPLv3)
 * - Pimcore Enterprise License (PEL)
 * Full copyright and license information is available in
 * LICENSE.md which is distributed with this source code.
 *
 * @copyright  Copyright (c) Pimcore GmbH (http://www.pimcore.org)
 * @license    http://www.pimcore.org/license     GPLv3 and PEL
 */
namespace App;
use HWI\Bundle\OAuthBundle\HWIOAuthBundle;
use Pimcore\HttpKernel\BundleCollection\BundleCollection;
use Pimcore\Kernel as PimcoreKernel;
class Kernel extends PimcoreKernel
{
    /**
     * Adds bundles to register to the bundle collection. The collection is able
     * to handle priorities and environment specific bundles.
     *
     * @param BundleCollection $collection
     */
    public function registerBundlesToCollection(BundleCollection $collection)
    {
        // activate bundle for SSO oauth login/register functionality
        if (class_exists('\Http\HttplugBundle\HttplugBundle')) {
            $collection->addBundle( new \Http\HttplugBundle\HttplugBundle());

**Comment by scrummer** [comment]
@fritzbrandbiz @fritzds 
As mentioned above, you don't have to add this to the Kernel as, altough Pimcore bundles are similar to Symfony bundles, Pimcore loads them automatically.
Once you required it via composer you can either enable it in the backend in the bundles manager or you can use the command line to enable/install it.
There is no need to register it in the Kernel manually.

**Comment by fritzds** [comment]
hi 

I have tried that but i keep getting this error "[ERROR] Bundle "FormBuilderBundle" is no valid bundle identifier "
