### ISSUE TITLE
Path not found

### ISSUE THREAD

**Issue by manuelkleinert** [dachcom-digital/pimcore-formbuilder#2]
After installing all pages no longer work. Get the following error:

Zend_View_Exception
script 'content/standard.php' not found in path (/var/www/vhosts/huelfsgesellschaft.pimdev.ch/httpdocs/website/views/layouts/formbuilder/:/var/www/vhosts/huelfsgesellschaft.pimdev.ch/httpdocs/website/views/scripts/formbuilder/:/var/www/vhosts/huelfsgesellschaft.pimdev.ch/httpdocs/plugins/Formbuilder/views/layouts/:/var/www/vhosts/huelfsgesellschaft.pimdev.ch/httpdocs/plugins/Formbuilder/views/scripts/:./views/layouts/:./views/scripts/)

![unbenannt](https://cloud.githubusercontent.com/assets/1038688/17138889/98650412-5342-11e6-9dde-18795c257e77.PNG)

**Comment by solverat** [comment]
Hi,

this has nothing to do with the formbuilder i think. your controller is requesting the standard view, wich is not available. 

So youre right setup would be:

**Website Setting**
![bildschirmfoto 2016-07-26 um 15 26 38](https://cloud.githubusercontent.com/assets/700119/17139581/69c4c4dc-5345-11e6-883e-fe9c754e11e5.png)

**Controller**
![bildschirmfoto 2016-07-26 um 15 27 23](https://cloud.githubusercontent.com/assets/700119/17139633/8fe42f40-5345-11e6-8bf1-310521ba9d0c.png)

**View**
![bildschirmfoto 2016-07-26 um 15 27 46](https://cloud.githubusercontent.com/assets/700119/17139643/98bf6d3c-5345-11e6-99bd-54c7e6143eb3.png)

**Comment by manuelkleinert** [comment]
Thank you for your quick response. The standard request is defined...

![unbenannt](https://cloud.githubusercontent.com/assets/1038688/17176140/987d1e8e-540b-11e6-914b-44b786bf906e.PNG)

**Comment by dpfaffenbauer** [comment]
In fact, thats a real issue with form-builder. I don't know why, but the controller plugin somehow overwrites the scripts-path:

Without Formbuilder, my script-paths look like this:
```
Array
(
    [0] => /*****/website/views/layouts/
    [1] => /*****/website/views/scripts/
    [2] => ./views/layouts/
    [3] => ./views/scripts/
)
```

With Formbuilder installed, it looks like this:

```
Array
(
    [0] => /*****/website/views/layouts/formbuilder/
    [1] => /*****/website/views/scripts/formbuilder/
    [2] => /*****/plugins/Formbuilder/views/layouts/
    [3] => /*****/plugins/Formbuilder/views/scripts/
    [4] => ./views/layouts/
    [5] => ./views/scripts/
)
```

I am going to further investigate on this.... but the issue should be re-opened.

**Comment by dpfaffenbauer** [comment]
I am actually really surprised that this ever worked on your environment....

the problem is occurs in \Zend_Controller_Action_Helper_ViewRenderer:498. It checks if the website/view path *or any subfolder* already exists within the path variable. Since Formbuilder adds the website path, it already exists and won't add the website/scripts path.

Possible Solution: Get rid of that plugin and manually add the paths for the Formbuilder!

**Comment by solverat** [comment]
Fixed! Thanks! Be sure you've checked the install advices: https://github.com/dachcom-digital/pimcore-formbuilder/blob/master/README.md#Installation
