### ISSUE TITLE
[bug] In Debug mode, Admin email always sent with blank To and Cc

### ISSUE THREAD

**Issue by ceefour** [dachcom-digital/pimcore-formbuilder#203]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

formbuilder version: dev-master 129d521

Pimcore v6.3.3

Debug IP Address enabled.

Form submit says "sent successfully" and it was in history, but To and Cc is always blank. However, weirdly, the "debug email view" shows the To and Cc correctly. see screenshots below:

![chrome_ZHC1XEiYb2](https://user-images.githubusercontent.com/24123/69874983-fcbd4400-12ee-11ea-9108-dc94b77265a2.png)

![chrome_rFg86sfrRr](https://user-images.githubusercontent.com/24123/69874992-0181f800-12ef-11ea-9498-0943b30485db.png)

![chrome_XhN8FPVOmk](https://user-images.githubusercontent.com/24123/69874995-05ae1580-12ef-11ea-9142-a12118291d3a.png)

**Comment by ceefour** [comment]
Log confirms this: (notice that the `to` and `cc` are `null`)

```
[2019-11-30 14:18:42] doctrine.DEBUG: UPDATE email_log SET `id` = ?, `documentId` = ?, `params` = ?, `requestUri` = ?, `from` = ?, `replyTo` = ?, `to` = ?, `cc` = ?, `bcc` = ?, `sentDate` = ?, `subject` = ? WHERE `id` = ? [10,194,"[{\"key\":\"container_3981_fu [...]","/id/edu/parent-lead?send=true","hello@lovia.life",null,null,null,null,1575098322,"Debug email: Hore new form",10] []
```

**Comment by solverat** [comment]
Yes. As long you're in debug mode, no mails will be sent to any defined users but only to your admin email. Try to turn off the debug mode!
