### ISSUE TITLE
Form success redirect displays redirect path as flash message

### ISSUE THREAD

**Issue by alexej-d** [dachcom-digital/pimcore-formbuilder#209]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

It seems that [this line](https://github.com/dachcom-digital/pimcore-formbuilder/blob/master/src/FormBuilderBundle/EventListener/MailListener.php#L264) sets the success message to the target document's path which is pretty weird and probably not intended. Why set the message at all in this condition? Or if you have to set the message, maybe set it to the content of the mail_successfully_sent_flash_message property?

**Comment by solverat** [comment]
@alexej-d nope, this is totally intended. From the docs:

![image](https://user-images.githubusercontent.com/700119/73642488-0f972080-4672-11ea-92a0-97458880402b.png)

The message property here can be ignored since you want to redirect the user to another page which means, the message itself has no further purpose.

**Comment by alexej-d** [comment]
@solverat I think you are mistaken. Even though one defines a redirect target, in addition to redirecting this bundle also shows the target's path as a flash message. If one uses "mail_succesfully_send_flash_message" it only gets appended to the messages array.

To for instance I want to redirect to "/thank-you" and show the message "All went well", the form submission redirects to /thank-you and TWO messages are displayed:

- "/thank-you" and
- "All went well"

**Comment by alexej-d** [comment]
I'm sorry to nag, but this behavior still persists. Could you please reopen?
