### ISSUE TITLE
Compatibility Pimcore 6.4 and higher

### ISSUE THREAD

**Issue by tobiasfeldmethwalter** [dachcom-digital/pimcore-formbuilder#215]
Is there a date until when the form builder is compatible with Pimcore 6.4 and higher? An error message currently appears after the integration.
Up to Pimcore 6.3.6 everything is fine

Thanks for your response.

**Comment by mc-supply** [comment]
I'm on version 6.5.1 of Pimcore with the dev-master version of Formbuilder and don't have any issues.

**Comment by mc-supply** [comment]
> Is there a date until when the form builder is compatible with Pimcore 6.4 and higher? An error message currently appears after the integration.
> Up to Pimcore 6.3.6 everything is fine
> 
> Thanks for your response.

I'm on version 6.5.1 of Pimcore with the dev-master version of Formbuilder and don't have any issues.

**Comment by solverat** [comment]
@tobiasfeldmethwalter formbuilder 3.2.0 / 3.2.1 works with pimcore 6.4 and also with pimcore 6.5.
