### ISSUE TITLE
Error integrating a form via snippet

### ISSUE THREAD

**Issue by tobiasfeldmethwalter** [dachcom-digital/pimcore-formbuilder#216]
If you insert a form into a snippet, you get the following form action and when you send the form a corresponding error message that the route cannot be found. How can the error be fixed with the "fragment" URL?

Thanks for your response

![form-snippet-bug](https://user-images.githubusercontent.com/38275746/75140357-050afc80-56ef-11ea-9c3d-3b138a13e60e.png)

**Comment by solverat** [comment]
Hey @tobiasfeldmethwalter: Please us https://talk.pimcore.org/ to ask questions about integration. If you think it's a bug, you need to provide some more information (exception, stacktrace and some reproducible steps)
