### ISSUE TITLE
E-Mail template shows Tag & Snippet Management

### ISSUE THREAD

**Issue by julmot** [dachcom-digital/pimcore-formbuilder#219]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

In the e-mail template "Formbuilder Email" Pimcore tag & snippet management will be shown. You can see it in this screenshot, embedding a freshchat button that has been configured using it. This of course doesn't get hidden, since this template doesn't embed our custom bundles main CSS file:

![000226](https://user-images.githubusercontent.com/8310677/80013175-c4e9af80-84ce-11ea-87e6-e17b68e3a6a4.png)

This might be confusing for editors and thus should be disabled.

Related:

* https://github.com/pimcore/data-hub/pull/202/files
* https://github.com/pimcore/pimcore/issues/6189

**Comment by solverat** [comment]
@julmot I think I need more info about this. Formbuilder comes with a very simple template which needs to be modified in 99% of all cases. What do you think we should provide here?

**Comment by julmot** [comment]
@solverat Thanks for the reply.

The problem here is that this feature is undocumented. But Pimcore offers the Tag & Snippet Management to embed custom snippets like a Google Tag Manager / Analytics etc.

The problem here is, that it doesn't offer a way to specifiy the location where these snippets are generated. Therefore, this is not a function that has to be called somewhere in the template or can be disabled in the template. It just manipulates the output with the provided code after everything has been generated.
You can only manage the position through the admin interface:

![000229](https://user-images.githubusercontent.com/8310677/80131473-976a3800-859a-11ea-9428-5b6b25b33ac0.png)

Therefore, currently tags and snippets are generated in the E-Mail preview of the formbuilder email. In my case this shows an unstyled Freshchat button that confuses our users. It was already the case in DataHub specific areas of the admin interface, as you can see [here](https://github.com/pimcore/data-hub/pull/202/files), they disabled it now.

To avoid that, it would probably be needed to override this in the formbuilder bundle for formbuilder specific areas of the admin interface.

**Comment by solverat** [comment]
Ah, now I got it (I think). But isn't that an issue for all email templates? FormBuilder just uses default pimcore email documents, so your snippet will show up on every other email template, right?

**Comment by julmot** [comment]
@solverat Yes, you're right. I haven't noticed earlier since the button is hidden by the frontend which is loaded in our custom templates, but not in formbuilder templates. Thanks for pointing out.

**Comment by solverat** [comment]
Isn't it possible to use a exclude pattern in your regex (something like `^/(?!(admin)).*$`)? However, is this ticket still related to formbuilder?

**Comment by julmot** [comment]
@solverat No, while the admin interface is located under the route `admin` the actual templates aren't. They are embedded in an iframe and have a route relative to the document tree where they are located. But I agree, it should be a solution from Pimcore itself.
