### ISSUE TITLE
Forms missing after upgrade

### ISSUE THREAD

**Issue by Sonja-Schubert** [dachcom-digital/pimcore-formbuilder#221]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no

Hi There,
I updated from 3.2.0 to 3.3.1 in a Pimcore 6.5.3. I updated via composer update.

Error Behaviour:
- My previous created form is not shown anymore in Form Builder Settings module and I cannot create new forms.

Error Message: 
Invalid form type configuration detected. Message was: An exception occurred while executing 'SELECT t0.id AS id_1, t0.`name` AS name_2, t0.success_management AS success_management_3, t0.form_definition AS form_definition_4 FROM formbuilder_output_workflow t0 WHERE t0.form_definition = ?' with params [2]: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'database-name.formbuilder_output_workflow' doesn't exist (/some-path/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php: 42)

Unfortunately I cannot see the update button in bundle manager anymore. Also the bin/console pimcore:bundle:update command does not do anything maybe cause I am already on the latest version. 

How can I fix the missing table and get my form back?

Thank you and kind regards,
Sonja

**Comment by solverat** [comment]
@Sonja-Schubert have you tried `bin/console pimcore:migrations:migrate -b FormBuilderBundle`?

**Comment by Sonja-Schubert** [comment]
@solverat Thank you for your fast reply. Unfortunately I didn't know this command. I tried it now and got the message that for FormBuilderBundle Migrations there are no migrations to execute.
Do I have to install or configure something additionally for this doctrine/dbal usage? Until now I worked with the DOA of pimcore only.

**Comment by solverat** [comment]
If you've updated via composer update, everything should be fine. There is a `migration` table in your database - check if version 20200304172137 has been added:

https://github.com/dachcom-digital/pimcore-formbuilder/blob/e7dc4a600a26b829cb93fe8ce9e024832a9b874b/src/FormBuilderBundle/Migrations/Version20200304172137.php

**Comment by Sonja-Schubert** [comment]
Ah thank you for the hint.
Solution for me was to remove the migration entries for FormBuilderBundle from migrations db table and enter the `bin/console pimcore:migrations:migrate -b FormBuilderBundle` command again. After this my form works again and I can create new forms.
