### ISSUE TITLE
Using dynamic recipients for form

### ISSUE THREAD

**Issue by Sonja-Schubert** [dachcom-digital/pimcore-formbuilder#222]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes

Hi All,
I would like to use a form with a dynamic email recipient. 

Situation:
Imagine a contacts database with a search for a contact person by category, zip or something else. On detail page of contact person/data object I would like to integrate the formsbuilder form id xy like in the docs twig example and set the recipient by param or something else. 
I don't want to create a mail template with own recipient for every contact person.

Is that possible? How?

Thank you and kind regards,
Sonja

**Comment by solverat** [comment]
There are several ways to achieve this. You could use form events to add some fields for example. The most simplest solution would be a custom option, I guess. Then use an outupt workflow event to modify your mail data. Example:
 
## Your Form
Create your form and add a workflow "test" with one channel "mail".

```twig
{% set config = {
    form_id: 13,
    form_template: 'bootstrap_4_layout.html.twig',
    output_workflow: 'test',
    custom_options : {
        contact_id: app.request.query.contactId {# find your contact id here #} 
    }
} %}

{{ form_builder_static(config) }}
```

## Your Service
```php
<?php

namespace AppBundle\Formbuilder;

use Pimcore\Mail;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use FormBuilderBundle\Event\OutputWorkflow\ChannelSubjectGuardEvent;
use FormBuilderBundle\FormBuilderEvents;

class EventListener implements EventSubscriberInterface
{
    public static function getSubscribedEvents()
    {
        return [
            FormBuilderEvents::OUTPUT_WORKFLOW_GUARD_SUBJECT_PRE_DISPATCH => 'event',
        ];
    }

    public function event(ChannelSubjectGuardEvent $event)
    {
        $subject = $event->getSubject();
        $workflowName = $event->getWorkflowName();

        if ($workflowName !== 'test') {
            return;
        }

        if (!$subject instanceof Mail) {
            return;
        }

        $formRuntimeOptions = $event->getFormRuntimeData();
        $customOptions = $formRuntimeOptions['custom_options'];

        if (!isset($customOptions['contact_id'])) {
            return;
        }

        $clientId = $customOptions['contact_id'];

        // [...]

        $yourContactMail = '[YOUR_LOGIC_HERE]';
        $subject->setTo($yourContactMail);
    }
}
```

Event Reference: https://github.com/dachcom-digital/pimcore-formbuilder/blob/master/docs/OutputWorkflow/30_Events.md

Hope this helps!
