### ISSUE TITLE
Pimcore 6.6.4 DB issues

### ISSUE THREAD

**Issue by justbane** [dachcom-digital/pimcore-formbuilder#225]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | /no

Just updated to Pimcore 6.6.4. When trying to open a form in the Admin section Form Builder Settings panel I receive this:

`Invalid form type configuration detected. Message was: An exception occurred while executing 'SELECT t0.id AS id_1, t0.`name` AS name_2, t0.success_management AS success_management_3, t0.form_definition AS form_definition_4 FROM formbuilder_output_workflow t0 WHERE t0.form_definition = ?' with params [7]: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'clientcom_stag_1561670500_master_PM_584.formbuilder_output_workflow' doesn't exist (/local/htdocs/_client/www.client.com/1561670500_master_PM_584/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php: 42)`

**Comment by solverat** [comment]
please migrate to the latest version, see #221.
