### ISSUE TITLE
Form not showing in BE & FE when a form label has more than 190 characters

### ISSUE THREAD

**Issue by gpalmisano** [dachcom-digital/pimcore-formbuilder#226]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? |no
| RFC?             | no

When label (e.g. a help-text) in the formdata is longer than 190 character, the form is not shown. neither in frontend nor in backend, and the toolbox element in the content page can not be edited anymore.

**Comment by solverat** [comment]
@gpalmisano This isn't a bug, since every label gets submitted to the pimcore translator, the label key can't be longer than 190 charactars ("Message ID's longer than 190 characters are invalid!").

**Comment by schmidt-travixmedia** [comment]
How about limitting the input field by maxlength attribute to 190 chars? Label texts containing more then 190 chars are pretty common for checkboxes, e.g. privacy statement agreement

**Comment by solverat** [comment]
@schmidt-travixmedia that's definitely something we should do. I just created a PR (#266) for that.
