### ISSUE TITLE
[BUG] Not blank for multifile upload flag will be ignored

### ISSUE THREAD

**Issue by plexmaniax** [dachcom-digital/pimcore-formbuilder#228]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

In my tests it does not matter if the "NOT BLANK FOR MULTIFILE UPLOAD FLAG" is set or not, it will be ignored.
Sending the form is always possible even if you don`t provide an upload.

Could you please check this.

**Comment by Homer0815** [comment]
I still have trouble with the validation of the multifile input type. The validation now kind of works but the error will not displayed in the frontend when using the Ajax functionality. Without Ajax it works as expected.

Configuration:
![image](https://user-images.githubusercontent.com/10532676/87659449-e240b980-c75d-11ea-89d9-ba89d7ebb206.png)

The validation request tho the controllers answers with the expected error: 
![image](https://user-images.githubusercontent.com/10532676/87659696-3b105200-c75e-11ea-8632-e7a04fe58568.png)

But the javascript part will not handle the error and display the error label on the website. Here is the result of the `formbuilder.error-field` event. The file upload field is missing: 
![image](https://user-images.githubusercontent.com/10532676/87659888-7f035700-c75e-11ea-8089-caa6f3c1ee95.png)

Result: 
![image](https://user-images.githubusercontent.com/10532676/87660036-b70a9a00-c75e-11ea-83d3-23996a6d761c.png)

**Comment by Homer0815** [comment]
Any new information right now? :)

**Comment by solverat** [comment]
see #236

**Comment by jeykodev** [comment]
@solverat thank you, i can confirm that everything is working as expected now! 👍
