### ISSUE TITLE
Dynamic Multi File will not be initialized (when using without Ajax)

### ISSUE THREAD

**Issue by jeykodev** [dachcom-digital/pimcore-formbuilder#230]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |no
| BC Break report? |no
| RFC?             |no

The Fineupload field will only be initialized when using the option `Ajax Submission` in the form options. Can you please check this?

**Comment by Homer0815** [comment]
Bump Bump - This is a pretty critical bug for us.

**Comment by solverat** [comment]
Well, currently it is not possible to initialize the AJAX uploader without AJAX forms (and never was). You could extract this method and implement it with your own needs.

https://github.com/dachcom-digital/pimcore-formbuilder/blob/39fa4957970aedd010258d76c8ec780c7f76b807/src/FormBuilderBundle/Resources/public/js/frontend/plugins/jquery.fb.core.form-builder.js#L250

**Comment by jeykodev** [comment]
@solverat ok, thank you for the hint.
