### ISSUE TITLE
Conditional Logic for Fieldset Container Fields

### ISSUE THREAD

**Issue by plexmaniax** [dachcom-digital/pimcore-formbuilder#232]
I`m not able to set a conditional logic out from repeater fields.

![www_voigt_ch____Pimcore](https://user-images.githubusercontent.com/18365319/88387215-53ade700-cdb2-11ea-8271-d1735239cedf.png)

**Comment by solverat** [comment]
This is currently not possible. Repeater fields are dynamic fields which means it's not possible to determinate user interactions (1-x repeatable blocks) in backend. 

But I think it should be possible with Fieldset container fields.

**Comment by JHeimbach** [comment]
Hey, 
I needed this feature so I looked into it: 

If we change the prefill in the EventSubscriber [here](https://github.com/dachcom-digital/pimcore-formbuilder/blob/master/src/FormBuilderBundle/EventSubscriber/FormBuilderSubscriber.php#L264) to this

```diff 
$subFieldData = isset($data[$field->getName()]) ? $data[$field->getName()] : [];
- $conditionalLogicOptions = array_merge(['formData' => $subFieldData, 'field' => null], $conditionalLogicBaseOptions);
+ $conditionalLogicOptions = array_merge(['formData' => $data, 'field' => null], $conditionalLogicBaseOptions);
$formTypeData = $this->addFormBuilderContainerField($field, $conditionalLogicOptions);
$form->add($formTypeData['name'], $formTypeData['type'], $formTypeData['options']);
```
the conditional setting and removing of constraints in fieldsets and repeater is working just fine.

**Comment by solverat** [comment]
Conditional Logic works now also with fields within fieldset containers!
