### ISSUE TITLE
[FIELDSSETS] No reorder & No logic

### ISSUE THREAD

**Issue by justbane** [dachcom-digital/pimcore-formbuilder#233]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

On Fieldsets:

You can not drag items into them, nor can you reorder items in the fieldset.

The logic panel will only let you select the Fieldset as a whole not the fields within it.

Version 3.3.4

**Comment by justbane** [comment]
Bump Bump - Has no one else had this issue? This is a pretty critical bug for us.

**Comment by Homer0815** [comment]
+1 for this issue. Feedback would be pretty nice!

**Comment by solverat** [comment]
see #231
