### ISSUE TITLE
[Bug/Feature Request] Validate empty forms

### ISSUE THREAD

**Issue by plexmaniax** [dachcom-digital/pimcore-formbuilder#235]
**current behavior**

If you set an empty form in the formbuilder container, the backend view will brake.

**should behaviour**

There should be a check and validation of the forms. If the form is empty for any reason (stupid costumers), there should be a prompt message "The form you`ve chosen is empty, please fill up the form"

**Comment by solverat** [comment]
Not reproducable: 

![image](https://user-images.githubusercontent.com/700119/97329087-f9239b80-1876-11eb-839e-d32ef43e538d.png)
![image](https://user-images.githubusercontent.com/700119/97329169-1193b600-1877-11eb-90b1-6719b2fb07de.png)
