### ISSUE TITLE
Show fully generated field name 

### ISSUE THREAD

**Issue by pascalmoser** [dachcom-digital/pimcore-formbuilder#237]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no

Currently it is not clear what the field is called to use it as placeholder in the Email template.
E.g. add a Text-Field with name 'email' and drop it in a Fieldset-Container. The placeholder in the template is now 'fieldname_xy_email'.

Suggestion: place a read-only-field in the form configuration with the placeholder name for each field.

**Comment by solverat** [comment]
![image](https://user-images.githubusercontent.com/700119/117871542-c9316800-b29d-11eb-82f6-7e9799ded95e.png)

To copy label for placeholders for example.

**Comment by solverat** [comment]
fixed with #279
