### ISSUE TITLE
[Request] Modify compatible form field types for object mappings

### ISSUE THREAD

**Issue by alexej-d** [dachcom-digital/pimcore-formbuilder#238]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

In https://github.com/dachcom-digital/pimcore-formbuilder/blob/master/docs/OutputWorkflow/11_ObjectChannel.md there is a list of possible mappings under "Available Mapping Data". The list is pretty short, could one modify some mapping or create new ones? Like for example mapping a text input to pimcore's email field type?

**Comment by solverat** [comment]
New Fields have been added (Mostly all CRM fields and the slider field):

https://github.com/dachcom-digital/pimcore-formbuilder/blob/3.x/docs/OutputWorkflow/11_ObjectChannel.md#available-mapping-data
