### ISSUE TITLE
Add Email-Options to Mail Channel

### ISSUE THREAD

**Issue by plexmaniax** [dachcom-digital/pimcore-formbuilder#245]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

It should be possible to overwrite mailsettings for a outputworkflow "E-Mail-Channel"

You ve got multi forms on your website, but its always the same formdata. Even the recipient changed sometimes.
On page A the mail should be sent to mail-a@domain.tld on page B the mail should be sent to mail-b@domain.tld. 

Actually, I have to create 2 different mails to handle this job even the difference is just the recipient.
It would be great if I could overwrite the mailadress direct through the E-Mail-Channel Settings as we already discussed.

**Comment by solverat** [comment]
As discussed internally, we'll postpone this feature. This would introduce a lot of "duplicate" fields (channel <=> email) which probably leads to more confusion than improvement!
