### ISSUE TITLE
Add charlimit validation in admin area

### ISSUE THREAD

**Issue by JHeimbach** [dachcom-digital/pimcore-formbuilder#255]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

Symfony forms throws an error "Message ID's longer than 190 characters are invalid!" when the label is longer than 190 chars.
AFAIK the form name is already limited to 190 characters but not the input names and labels. 

Is there an easy way to add a validation to the form builder settings?

**Comment by solverat** [comment]
I think there is a misunderstanding. All form(builders) labels will be submitted to the pimcore translator. If you're using labels longer than 190 chars, the error message "longer than 190..." will show up.  It's a good practice to use dot notated keys in formbuilder label rows (like `form.label.first_name`) and translate them in pimcores website translation panel afterwards. 

Feel free to reopen this issue if something is missing!
