### ISSUE TITLE
Attach file to email not working

### ISSUE THREAD

**Issue by synchmann** [dachcom-digital/pimcore-formbuilder#256]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Hi,
I've created a form with a dynamic file input. When submitting the form an email is sent, but the file is not attached. I've checked `send files as attachment` and `allow attachment`, but nothing appears in the mail. Can't find any tips in the documentation. 
The file appears in the assets tree.

**Comment by solverat** [comment]
Could you please check the email log in pimcore? 

![image](https://user-images.githubusercontent.com/700119/117841171-1c46f300-b27d-11eb-9487-67ff767ad27e.png)

Checkout the parameters - any linked attachment?

**Comment by solverat** [comment]
We also covered the file upload in a dedicated test (https://github.com/dachcom-digital/pimcore-formbuilder/blob/master/tests/acceptance/Form/FineUploaderCest.php) which allows me to say that this should work.

Please reopen this issue if you have more information!
