### ISSUE TITLE
"FormBuilderBundle\Form\Type\HoneypotType.php" vs "FormBuilderBundle\Form\Type\HoneyPotType.php"

### ISSUE THREAD

**Issue by RuudvdvNB** [dachcom-digital/pimcore-formbuilder#259]
HoneyPotType.php misspelled with corresponding class name HoneypotType.

This triggers errors in our projects with Pimcore 5.

**Comment by solverat** [comment]
@RuudvdvNB Thanks! I guess this is because composer 2 requires strict psr-4 standards now! Thanks!

**Comment by solverat** [comment]
@RuudvdvNB  i just released 2.7.7!

**Comment by RuudvdvNB** [comment]
@solverat thanks for the new version!
