### ISSUE TITLE
[FeatureREQ]Prevent formbuilder send mails from blacklisted mailaddresses

### ISSUE THREAD

**Issue by plexmaniax** [dachcom-digital/pimcore-formbuilder#271]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

Pimcore has a nice feature in his mailsettings called "Blacklist" 

<img width="465" alt="www_striebig_com____Pimcore" src="https://user-images.githubusercontent.com/18365319/111280308-f36afe80-863b-11eb-99c8-7617594fbfc2.png">

With this feature I could tell pimcore to stop sending mails to a special recepient.
This is very helpful to prevent some known SPAMER addresses let flooding your forms.

We use the workflow and fetches the recepient mailaddress (variable %mail%) filled in in the forms and send this information to the supports, servicedesks or normal costumer addresses. And this is the problem for now.

If I blacklist the emailaddress maik@test.ch in pimcore, I will no longer receive any email from this pimcore and thats fine.
Bbut the copy of my mail is still sent to the company, so the company get still the SPAM messages.

Is there a proper way to include the email blacklist settings from pimcore to stop processing the formbuilder if a blacklisted email was set in the form?

**Comment by solverat** [comment]
This works as expected. Pimcore checks `To` `Cc`, `Bcc` and `ReplyTo`. If you're using a custom placeholder, use the `replyTo` field to block potential spam addresses.
