### ISSUE TITLE
no label when placeholder

### ISSUE THREAD

**Issue by mediafant** [dachcom-digital/pimcore-formbuilder#273]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes

When I use placeholder in Form, most time it is not necessary to use labels for this form-fields. But some form-fields need label (checkbox ...).
So it would be helpful if it is possible to define a classname for the container in which label an input-field is located, so that it is possible to hide or design label-field with css.

**Comment by solverat** [comment]
Currently, there is no way to toggle the label in a convenient way. 
Adding more options as `label_attr` or `row_attr` blocks could be a solution, but I'm not sure if we're going to overcomplicate things here.

A solution for your project could be to check this in your template:


```twig
{# app/Resources/FormBuilderBundle/views/Form/Theme/bootstrap_4_layout.html.twig #}

{% extends "@!FormBuilder/Form/Theme/bootstrap_4_layout.html.twig" %}

{% block form_label -%}

    {% if 'placeholder' in attr|keys %}
        {% set label_attr = label_attr|merge({'class': label_attr['class']|default('') ~  ' d-none' }) %}
    {% endif %}

    {{ parent() }}

{%- endblock form_label %}
```

**Comment by mediafant** [comment]
@solverat - Thanks for this solution
