### ISSUE TITLE
[BUG]Attached files will always be added to the first mail in outputworflow order

### ISSUE THREAD

**Issue by plexmaniax** [dachcom-digital/pimcore-formbuilder#296]
| Q                | A
| ---------------- | -----
| Bug report?      | yes

### **current behavior**

When creating an email output with 2 mails, one for internal and one as confirmation for external, the mail is always attached to the first mail. It doesn't matter if you select the attachment or not.

### **reproduce**

Build a form with file upload and an output workflow with 2 different mails (internal and external). Send the form, change the order of the mails in the workflow and resend it. The attachment is always attached to the first mail.

**Comment by solverat** [comment]
Fixed via #321
