### ISSUE TITLE
Add Mail-Log Filter to Email Channel

### ISSUE THREAD

**Issue by plexmaniax** [dachcom-digital/pimcore-formbuilder#297]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

Time and again, there are customers who send their sensitive data via a form. As the operator of the site, I do not want this data to be stored in Pimcore. It would be good if you could define in an ouput-workflow whether the mails should be stored or not.

**current behavior**

Every single mail, in forms sent by pimcore will be stored in system files and database.

**shall behavior**

Give us the possibility to opt out the mailsavings by check box in the output workflow

**Comment by solverat** [comment]
![image](https://user-images.githubusercontent.com/700119/202383000-b0fcc0ff-7dcf-4619-bb77-e3ed500158b1.png)

**Comment by solverat** [comment]
Done
