### ISSUE TITLE
[BUG] Error on Form Submit

### ISSUE THREAD

**Issue by aweichler** [dachcom-digital/pimcore-formbuilder#299]
When you have a form with an output workflow but without a configuration for the workflow you get an exception on form submit.
`FormBuilderBundle\OutputWorkflow\SuccessManagementWorker::process` Method need to have a array but `FormBuilderBundle\Model\OutputWorkflowInterface` returns array or null. 
The method is called [in this file](https://github.com/dachcom-digital/pimcore-formbuilder/blob/c8d22cbc7faeb0499666e870ff1e653aed947808/src/FormBuilderBundle/OutputWorkflow/FormSubmissionFinisher.php#L84)

**Comment by solverat** [comment]
Although it makes not sense to use a workflow without any configuring, I've added another check to assert a valid error message. Fixed in 4.1.4
