### ISSUE TITLE
Object channel - map data object fields inside fieldsets

### ISSUE THREAD

**Issue by valentin-** [dachcom-digital/pimcore-formbuilder#300]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             |  no

---

Hi, I'm trying to save form data to an object. Unfortunately I can't map fields inside fieldsets, isn't that possible?

![image](https://user-images.githubusercontent.com/90033/142423902-07f2356d-d470-4a7b-9b64-a4f6d1233dff.png)

Thanks!

**Comment by shaselboeck** [comment]
Same here

**Comment by solverat** [comment]
Mhmm, it is **not** possible to map object properties to container items of type "repeater" but I guess it should be possible to map field set fields since they are simple subfields. I have to check this first.

**Comment by bellu** [comment]
Same thing seems to happen in the Email Workflow, i have only the fieldset in the builder.

**Comment by solverat** [comment]
@bellu you mean the [mail layout editor](https://github.com/dachcom-digital/pimcore-formbuilder/blob/master/docs/OutputWorkflow/10_EmailChannel.md#mail-layout-editor)? True, there are no subfields either. The Mail Layout Editor most meaningful purpose is to set up structured text emails (in some cases, provider will process text emails by automation). I would recommend using the  default twig template (`form-data.html.twig`) which will be used by the email output channel by default.

**Comment by shaselboeck** [comment]
@solverat: Will the bug be fixed?

**Comment by simonkey** [comment]
Any updates about this issue?

**Comment by hagmann** [comment]
We have the same issue. Did anyone find a workaround? @solverat is this going to be fixed?

**Comment by solverat** [comment]
@valentin-, @shaselboeck, @bellu, @simonkey, @hagmann: Finally, this works now!

Also thanks to @JHeimbach!

https://github.com/dachcom-digital/pimcore-formbuilder/pull/355

This will be available in 4.1.4!
