### ISSUE TITLE
Tailwind Support

### ISSUE THREAD

**Issue by ChrisB9** [dachcom-digital/pimcore-formbuilder#303]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

I really like the idea of this form builder and would like to integrate that for a clients project. I currently just have two issues, that stop me from using this:
I am neither using bootstrap nor jquery.

Both are currently a hard requirement, and that is a path i cannot go. Adding those two dependencies to my project would completely bloat everything up.

Recently Symfony Forms added the support for tailwindcss to form-templates. I can add a PR to provide the support here as well. The problem though lies within the jquery dependency. I saw you want to add alpine.js as an alternative, which I very much like, but would it be possible to add a vanilla-js version as well? That way there is support for everyone independent of their current used libraries.

**Comment by solverat** [comment]
Hey @ChrisB9. FormBuilder 4.x does not come with jQuery plugins anymore. Those are available via NPM (https://www.npmjs.com/package/jquery-pimcore-formbuilder). 

However, it is true that there is currently no alternative. But we're currently working on a Tailwind implementation. With that, we may provide vanilla JavaScript versions of those existing jQuery plugins.

**Comment by ChrisB9** [comment]
That's wonderful news! Do you have a rough timeline for that in mind?

**Comment by akno77** [comment]
We have the same problem. We don't use JQuery in our projects but would like to have the Formbuilder JS based features in vanilla JS. Are there any news concering this?

**Comment by solverat** [comment]
we published a dependency-free, vanilla js repostory for all formbuilder extendsions: https://www.npmjs.com/package/js-pimcore-formbuilder

Read more about it here: https://github.com/dachcom-digital/pimcore-formbuilder/blob/master/docs/91_Javascript.md
