### ISSUE TITLE
E-Mail CSV Export contains data of several forms when their Output Workflows share the same title.

### ISSUE THREAD

**Issue by anyMOTION-GRAPHICS** [dachcom-digital/pimcore-formbuilder#325]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

E-Mail CSV Export contains data of several forms when their Output Workflows share the same title.

Tested with 2 forms sharing the same Output Workflow title: After sending them off each 3 times, both exports had 6 entries. 
After renaming them different, those 6 entries were gone. Second try with different titles was successfull, only form-related entries in export. After renaming them again using the same title, exports include those 6 entries, again.

**Comment by anyMOTION-GRAPHICS** [comment]
@solverat is there any chance, that you could check that issue in a moment and give as a short reply, if it'll be possible to fix this soon?

**Comment by solverat** [comment]
@anyMOTION-GRAPHICS, yes confirmed.

**Comment by JHeimbach** [comment]
@solverat i have already prepared a solution for this, forgot to open a PR :( one moment please...

**Comment by solverat** [comment]
@JHeimbach Ah, I see. Pimcore is a dangerous place to be... I'll merge and release it later with 4.1.2. Thank you so much for your investigation!
