### ISSUE TITLE
DynamicMultiFile with multiple Pods (Kubernetes)

### ISSUE THREAD

**Issue by breakone** [dachcom-digital/pimcore-formbuilder#334]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

The `PIMCORE_SYSTEM_TEMP_DIRECTORY` is used in [FileLocator](https://github.com/dachcom-digital/pimcore-formbuilder/blob/master/src/FormBuilderBundle/Tool/FileLocator.php) to get the directories for saving files. So if a file upload with the DynamicMultiFile Element ([FileStream](https://github.com/dachcom-digital/pimcore-formbuilder/blob/7ab92f8f1e70d1241911e24e6d5ff7020ac7ce67/src/FormBuilderBundle/Stream/FileStream.php#L125)) is made in a stateless environment, the uploaded files may not exist and no files are appended in e.g. emails.

So the configured [File Storage](https://pimcore.com/docs/pimcore/10.0/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/File_Storage_Setup.html) should be used instead.

See also [https://github.com/pimcore/pimcore/issues/12174](https://github.com/pimcore/pimcore/issues/12174)

**Comment by solverat** [comment]
This is finally available and will be released in 4.3. It's basically an adoption of @dpfaffenbauer PR with some additional improvements. Thank you all for reporting/contributing!
