### ISSUE TITLE
Support for Pimcore 10.4 ?

### ISSUE THREAD

**Issue by kriscr** [dachcom-digital/pimcore-formbuilder#337]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

Will there be support for Pimcore 10.4?

**Comment by scrummer** [comment]
Hi @kriscr 
Event though it says 10.3 in the README the bundle should be fully compatible with 10.4 and even 10.5.

BR Scrummer

**Comment by scrummer** [comment]
Small correction: The new release (v4.1.2) is now compatible with 10.5.
