### ISSUE TITLE
Respect PSR-1 and PSR-2 Formatting / apply JS Beautify

### ISSUE THREAD

**Issue by solverat** [dachcom-digital/pimcore-formbuilder#35]
- Format PHP Code
- JSLint for Javascript

**Comment by Yivan** [comment]
@solverat Thanks for making your plugin even better!
I was just seeing this issue for PSR formatting, and I have seen you use uppercase for null, false, ... (NULL, FALSE, ...). From what i know PSR say it must be lowercase if i am not wrong (see here please: http://www.php-fig.org/psr/psr-2/#keywords-and-truefalsenull).
It is not a problem as code is ok, but it is worth to mention it maybe.
Thanks again!

**Comment by solverat** [comment]
hey @Yivan, those are some additional rules from our side:
- uppercase ```NULL,FALSE,TRUE```
- "align key-value pairs" in arrays.

**Comment by Yivan** [comment]
Ok thanks for your fast answer, i undestand better ; )
