### ISSUE TITLE
[BUG] Form config import broken

### ISSUE THREAD

**Issue by alexej-d** [dachcom-digital/pimcore-formbuilder#371]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

It looks like the new funnel functionality breaks the importing of form config yaml files. I have received the following error with a simple form:

```
Error while importing form definition: An exception occurred while executing 'INSERT INTO formbuilder_output_workflow (`name`, funnel_workflow, success_management, form_definition) VALUES (?, ?, ?, ?)' with params ["SubmitMail", null, "N;", 1]: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'funnel_workflow' cannot be null
```

Note: I am not using funnels.

**Comment by solverat** [comment]
@alexej-d Thanks for reporting! This has been fixed in #371 and is available in 4.2.2, which just got released.
