### ISSUE TITLE
[BUG] Field collections are not saved in the created object

### ISSUE THREAD

**Issue by patrickpahlke03** [dachcom-digital/pimcore-formbuilder#375]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

When creating an object with field collections, they are not saved in the object.

I have already looked at the code and think I have found the error. In the "AbstractObjectResolver" class in line 271 there is a "return". But I think there must be a "continue", at least it works when there is a "continue". 
![Bildschirmfoto 2023-01-23 um 11 58 39](https://user-images.githubusercontent.com/69801380/214023358-7e61dbf0-80bf-4136-9ce4-aaca31cf9044.png)

Could you please have a look at this?

**Comment by solverat** [comment]
@patrickpahlke03 Good catch, that's wrong indeed. We never stumbled on that, because if you populate all fields in your field collection, this early return never kicks in.

Thanks for your investigation!
