### ISSUE TITLE
Prevent "/_locale/form-control/get-url-structure" from being indexed

### ISSUE THREAD

**Issue by scrummer** [dachcom-digital/pimcore-formbuilder#383]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | no
| BC Break report? | no
| RFC?             | no

The get-url-structure endpoint needs to be excluded from indexing robots (robots.txt). Install it by making an entry for each site:
```
...
/form-control/get-url-structure
/*/form-control/get-url-structure
```

@see https://github.com/pimcore/pimcore/blob/10.5/bundles/AdminBundle/Controller/Admin/SettingsController.php#L1571-L1608

**Comment by solverat** [comment]
Allowing `GET` operation on this route should be enough. Those URLs are now secret.

Btw. BingBot is the only silly Bot which is crawling data-attributes. However. Fixed.
