### ISSUE TITLE
Pimcore 11 Support

### ISSUE THREAD

**Issue by dpfaffenbauer** [dachcom-digital/pimcore-formbuilder#400]

**Comment by JustMe69** [comment]
is there a timeline when this feature would be ready to use?

**Comment by solverat** [comment]
Hey folks, we're currently working hard on the p11 release. we absolutely want to add the email editor feature - which requires some time and heavy coding - the release will be available in the upcoming weeks.

**Comment by solverat** [comment]
Update: dev-master is now ready for P11.
