### ISSUE TITLE
4.5 is failing on 10.6. (You have requested a non-existent service FormDefinitionFactoryInterface)

### ISSUE THREAD

**Issue by danielerne** [dachcom-digital/pimcore-formbuilder#401]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes

Hi we want to use the formbuilder on 10.6 but it fails when we want to enable the bundle. 
Composer install was successful.

bin/console pimcore:bundle:install FormBuilderBundle

<img width="977" alt="Bildschirmfoto 2023-07-04 um 17 56 24" src="https://github.com/dachcom-digital/pimcore-formbuilder/assets/546931/a5e9db74-6ae0-40ab-a03c-3dbcd00721a6">

**Comment by solverat** [comment]
@danielerne I can't reproduce it. I also just updated the test matrix to p10.6 and all tests are running on 10.6 without any issue. 
Must be something on your side.

**Comment by danielerne** [comment]
Thanks. It was a cache issue. If somebody else has the issue:
Clean the cache folders manually. And then manually enable and install the extension again.
