### ISSUE TITLE
Missing translations for Zend_Form standard error messages

### ISSUE THREAD

**Issue by wsung** [dachcom-digital/pimcore-formbuilder#42]
Hi, I have some problems translations.  I take an input field and check required to true, When I submit the form, every labels and messages are in the right language. Only the errors from Zend_Form like "isEmpty'. I'm only get "Value is required and can't be empty" are still in english. But if I put the translation into the json file, like form_1_de_DE.json, the translation works. Is this the right way?

**Comment by solverat** [comment]
Hey wsung. All the default error messages will be loaded from the default [zend validator directory](https://github.com/dachcom-digital/pimcore-formbuilder/blob/master/static/lang/errors/en/Zend_Validate.php). If you need some custom messages you can use the validator (right click on element => add validator).
