### ISSUE TITLE
[BUG] Is invalid class being added when visibility changes

### ISSUE THREAD

**Issue by JoeyDaems** [dachcom-digital/pimcore-formbuilder#422]
### Discussed in https://github.com/dachcom-digital/pimcore-formbuilder/discussions/414

<div type='discussions-op-text'>

<sup>Originally posted by **JoeyNtriga** September 27, 2023</sup>
Hi,

On this page we have a form that uses the build in conditional logic to show/hide two input fields.
The two fields should be required when they are visible so i add validation based on if they are visible or not.
The problem we are facing is when the fields become visible (they are hidden by default), the class is-invalid automatically gets added to the fields resulting in the fields looking like they were incorrectly submitted while this isn't the case.

The project is using pimcore version 10.6.3 and formbuilder version 4.5.0.

Did we set it up wrong or is this a bug?

Here is whats happening:

https://github.com/dachcom-digital/pimcore-formbuilder/assets/130968595/4fad2615-85f3-4f02-9b50-09969c817bb2

<img width="1166" alt="Screenshot 2023-09-27 at 13 42 20" src="https://github.com/dachcom-digital/pimcore-formbuilder/assets/130968595/b249cb36-150b-495f-817c-1708f23ddcf2">
<img width="804" alt="Screenshot 2023-09-27 at 13 42 35" src="https://github.com/dachcom-digital/pimcore-formbuilder/assets/130968595/dfdcbaeb-0949-44f6-b6d6-4c360f30163c">

</div>

Thanks in advance!

**Comment by solverat** [comment]
@JoeyNtriga I guess you're using the https://github.com/dachcom-digital/js-pimcore-formbuilder extension? 

Since this is a frontend only issue, we should move this issue, wdyt @pascalmoser?

**Comment by JoeyNtriga** [comment]
I am, the latest version(1.0.8) is running in the example.

**Comment by solverat** [comment]
@JoeyNtriga Thanks, I'm closing this in favor to https://github.com/dachcom-digital/js-pimcore-formbuilder/issues/20
