### ISSUE TITLE
Mail Layout Editor broken

### ISSUE THREAD

**Issue by valentin-** [dachcom-digital/pimcore-formbuilder#426]
| Q                | A      |
|------------------|--------|
| Bug report?      | yes |
| Feature request? | no |
| BC Break report? | no |
| RFC?             | no |

Hi, it's not possible to edit the fields for Output Workflow -> Mail Layout Editor. Possible caused by the wysiwyg update.

![image](https://github.com/dachcom-digital/pimcore-formbuilder/assets/90033/0f54aa6c-7409-496c-8b11-0219af0cbc1a)

Pimcore 11.1.1, Formbuilder 5.0.1

Cheers,
Valentin

**Comment by solverat** [comment]
@valentin- thanks for reporting. In my dev environment I've `PIMCORE_DEV_MODE` enabled to true, therefor I never stumbled on that. Fixed in 5.0.2!
