### ISSUE TITLE
Edit button z-index issue

### ISSUE THREAD

**Issue by Nadermane** [dachcom-digital/pimcore-formbuilder#44]
Hello, yet another issue, this time for the edit button in a document (css class: `pimcore_area_edit_button_content pimcore_area_edit_button`). It seems to always be located under the form, disallowing easy access to it and therefor blocking content editing. I've seen in `/Formbuilder/static/css/admin.css` that you already attempted a fix but this does not seem to work. Maybe `!important` is missing or the load order of this css is too early and getting overwritten by default css? I'll leave it up to you, just reporting the issue here. :-)

**Comment by solverat** [comment]
true story, you've found a relict. :) the css won't work because its in the wrong css file (global admin css, not editmode css)
