### ISSUE TITLE
Range Validator missing min/max config Fields in Admin UI

### ISSUE THREAD

**Issue by ehaeusler** [dachcom-digital/pimcore-formbuilder#441]
| Q                | A      |
|------------------|--------|
| Bug report?      | yes |
| Feature request? | no |
| BC Break report? | no |
| RFC?             | no |

Pimcore Version: 11.1.4
Formbuilder-Version: 5.0.3

I recently recreated forms of an old formbuilder version in a new project. It looks like the Range Validator is missing the configuration fields for min and max Values, only minPropertyPath and maxPropertyPath are shown in the backend:

![Bildschirmfoto 2024-03-22 um 10 33 49](https://github.com/dachcom-digital/pimcore-formbuilder/assets/822623/e6211337-3bd8-47d0-8784-d2e3043c12d2)

For example the same screen in the old formbuilder:

![Bildschirmfoto 2024-03-22 um 10 33 39](https://github.com/dachcom-digital/pimcore-formbuilder/assets/822623/ca167dd1-ce1b-4fd6-85fc-cf43c893ad25)

The corresponding validator class still has those fields though:

![Bildschirmfoto 2024-03-22 um 10 34 38](https://github.com/dachcom-digital/pimcore-formbuilder/assets/822623/bfa5efea-2785-4cca-b960-869b93a98be1)

**Comment by solverat** [comment]
Fixed with #452!
