### ISSUE TITLE
Clarify that emails not sended in dev mode

### ISSUE THREAD

**Issue by nosovk** [dachcom-digital/pimcore-formbuilder#460]
| Q                | A      |
|------------------|--------|
| Bug report?      | no |
| Feature request? | no |
| BC Break report? | no |
| RFC?             | no |

It's unclear, from current documentation, that you have to switch symphony to prod env to get emails going. In dev mode, only debug emails sent.

**Comment by solverat** [comment]
@nosovk FormBuilder is using PIMCORE standard mail submission workflow (`$mail->send()`) which means you have to check out their documentation:

> If the Debug Mode is enabled, all emails will be sent to the Debug Email recipients defined in Settings > System > Debug > Debug Email Addresses. Additionally the debug information (to whom the email would have been sent) is appended to the email and the Subject contains the prefix "Debug email:".
 – https://pimcore.com/docs/platform/Pimcore/Development_Tools_and_Details/Email_Framework/
