### ISSUE TITLE
Migration "Version20240819150642" fails after bundle installation

### ISSUE THREAD

**Issue by bk-hitcom** [dachcom-digital/pimcore-formbuilder#473]
When installing the bundle in Pimcore 11.3 and then doing a "doctrine:migrations:migrate", the migration Version20240819150642 fails because the "mailLayout" table column does not exist. (Line 27) It should be checked whether the column to be deleted really exists.
Affected version v5.1.0

**Comment by solverat** [comment]
@bk-hitcom Thanks for the report. Fixed and released within [5.1.1](https://github.com/dachcom-digital/pimcore-formbuilder/pull/474).
