### ISSUE TITLE
Inheritance issue setting up a custom workflow channel

### ISSUE THREAD

**Issue by bbdammert** [dachcom-digital/pimcore-formbuilder#493]
| Q                | A      |
|------------------|--------|
| Bug report?      | yes |
| Feature request? | no |
| BC Break report? | no |
| RFC?             | no |

Environment: Pimcore 11.3.1, FormBuilderBundle 5.1.4

I'm trying to setup a custom workflow channel, following the steps described in the [documentation](https://github.com/dachcom-digital/pimcore-formbuilder/blob/v5.1.4/docs/OutputWorkflow/12_CustomChannel.md).

The first issue is with the documentation itself: using the code examples without any changes and registering the ExtJS class using the `\Pimcore\Event\BundleManagerEvents::JS_PATHS` event, results in an internal error, as `\App\FormBuilder\MyChannel::getUsedFormFieldNames()` and `\App\FormBuilder\MyChannel::dispatchOutputProcessing()` lack the required return types.

After adding the return types, I see the new workflow channel in the workflow settings of a form. Selecting it, results in a Javascript error message: `Uncaught TypeError: channelConfigPanel.setVirtualFunnelAware is not a function`. It seems, inheritance doesn't work.

Changing the name in the ExtJS class to `Formbuilder.extjs.formPanel.outputWorkflow.channel.my` (i.e. removing the `Channel` suffix as with the integrated workflow channels) removes this error. But then, no configuration is found (message
_No configuration for myChannel found._ instead of the configuration form). Additionally removing the `Channel` suffix in the service registration in `services.yaml`, makes the initial Javascript error message reappear.

**Comment by solverat** [comment]
@bbdammert Thanks for your Report.

I'll update the docs, since they seem to be a bit outdated. However, your ExtJs issue is a priority problem! 

```php

    public static function getSubscribedEvents(): array
    {
        return [
            # make sure, the priority is low to load fb resources first!
            BundleManagerEvents::JS_PATHS => ['addJsFiles', -255], 
        ];
    }

    public function addJsFiles(PathsEvent $event): void
    {
        $event->addPaths([
            '/path/to/your/channel.js'
        ]);
    }
```
I just checked it by myself and everything works as expected:

![image](https://github.com/user-attachments/assets/2515f732-df02-4087-8e64-87b39183f857)
