### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by geekdevs** [dachcom-digital/pimcore-formbuilder#50]
Is there anything specific I need to do in order to install this other then adding to composer and to `AppKernel.php`?

Because when I did so I found that SQL dump is not imported and it is crashing as it failed to find `formbuilder_forms` table.

**Comment by solverat** [comment]
hi @geekdevs, all our bundles are real pimcore extensions which means you don't have to add them to the appkernel but activate and install them through the admin backend.
