### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by geekdevs** [dachcom-digital/pimcore-formbuilder#52]
Sorry to bother you again @solverat, but now I have issues with installing this bundle.

Trying to install with latest pimcore build 108. 

`composer require dachcom-digital/pimcore-formbuilder:dev-master#33296eca98b88fa13355204aa47085542b041e5f`

And then with `bin/console pimcore:bundle:list` it does not appear. It's also not visible on admin interface. What am I doing wrong?

Does it conflict with members plugin maybe?

**Comment by geekdevs** [comment]
ok, I have just re-tested it with fresh installation (without any other plugins) and it still does not show up.

**Comment by solverat** [comment]
This is not a support board. please use the [community forum](https://talk.pimcore.org/) or gitter. 
Try to use the `composer dump-autoload` function. 
Since we're using this bundle already in production you probably have some misconfiguration on your system.

**Comment by geekdevs** [comment]
@solverat ok, yes. Will try that, thanks. Could you just let me know which version you're using in production (both plugin and pimcore)?
I don't think I have misconfiguration though because I use the same setup for installing members plugin and that works (on fresh pimcore).

**Comment by geekdevs** [comment]
@solverat it looks like there's an issue with packagist (it pulls incorrect version of this bundle). Could you check it?

**Comment by geekdevs** [comment]
Just try to install this with composer - it won't work. I asked my colleague to try- same issue.

**Comment by solverat** [comment]
it's 
`"dachcom-digital/formbuilder" : "dev-master"` 
not 
`"dachcom-digital/pimcore-formbuilder" : "dev-master"`

**Comment by geekdevs** [comment]
thank you, that one I confused with repository name
