### ISSUE TITLE
Form Area Brick - Edit Button does not work

### ISSUE THREAD

**Issue by js-aw** [dachcom-digital/pimcore-formbuilder#61]
I have installed the bundle, created a form and used the form brick on a page. When I click on the Edit button to configure the form, nothing happens. the edit button should open a dialog?

**Comment by solverat** [comment]
he @js-aw, just checked it and it worked as aspected. sometimes the pimcore edit buttons get rearranged (z-index, overlays etc.) depending on your project style.
