### ISSUE TITLE
How to create a form to choose in edit dialog?

### ISSUE THREAD

**Issue by choppe3766** [dachcom-digital/pimcore-formbuilder#80]
I've installed the formbuilder plugin and all seems ok.
But how can I generate a form, which is selectable in the edit dialog?

![bildschirmfoto 2018-03-21 um 20 49 47](https://user-images.githubusercontent.com/6122199/37733846-b1ce8dd2-2d49-11e8-97c9-4fc5785c77e9.png)

Thanks for your help ;-)
Chris

**Comment by AndiKeiser** [comment]
Hey Chris
You have to add a form first. Under Settings -> Form Builder Settings.

**Comment by solverat** [comment]
@choppe3766 please use the [community](talk.pimcore.org) for support questions. As @AndiKeiser already mentioned, you need to add some forms first.
