### ISSUE TITLE
Layout Component

### ISSUE THREAD

**Issue by RuudvdvNB** [dachcom-digital/pimcore-formbuilder#89]
Just started using this bundle and still trying out before we can use it in our projects.

There is one function that would be awesome to see, adding layout components just like classes that can be created in Pimcore.

This way we can easily group fields (with or without titles). 

Would that be possible?

**Comment by solverat** [comment]
Hey @RuudvdvNB. Currently this is not possible. There are field layouts (half, third, full) which are extendable but no grouping functionality. But it's on our roadmap (see #68).

**Comment by solverat** [comment]
Hey @RuudvdvNB: We just merged the [container feature](https://github.com/dachcom-digital/pimcore-formbuilder/blob/master/docs/83_ContainerType.md) which also supports fieldsets.
