### ISSUE TITLE
Form import currently not working

### ISSUE THREAD

**Issue by scrummer** [dachcom-digital/pimcore-formbuilder#96]
When importing a YML-form the backend throws an exception: `TypeError: Cannot read property 'getItems' of null`

See: [form.js -> Form.onTreeNodeBeforeSelect](https://github.com/dachcom-digital/pimcore-formbuilder/blob/master/src/FormBuilderBundle/Resources/public/js/comp/form.js#L264)

**Comment by solverat** [comment]
also related with #92
